package com.krayo.art.constants

enum class Destinations {
    HOME,
    DISCOVER,
    CONTENT_CREATION,
    CONTENT_CREATION_OPTIONS,
    PRODUCT_CREATION,
    ADD_PRODUCT,
    CHAT,
    PROFILE,
    ANALYTICS,
    AUTHENTICATION,
    COMMUNITIES,
    DASHBOARD,
    CONTENT_SEARCH,
    ONBOARDING,
    ONBOARDING_PROCESS,
    ONBOARDING_BEGIN
    SEARCH_RESULTS,
    ACCOUNT_CREATION,
    EMAIL_VERIFICATION,
    AUTH_SUCCESS,
}