package com.krayo.art.constants

enum class Destinations {
    HOME,
    DISCOVER,
    CONTENT_CREATION,
    CONTENT_CREATION_OPTIONS,
    PRODUCT_CREATION,
    LAST_CAPTURED_CONTENT,
    ADD_PRODUCT,
    CHATS,
    JoinCommunities,
    PROFILE,
    ANALYTICS,
    AUTHENTICATION,
    DASHBOARD,
    ORDER_VIEW,
    DISPATCH_SUCCESS,
    CANCEL_ORDER,
    ORDER_CHECKOUT,
    CONTENT_SEARCH,
    ONBOARDING,
    ONBOARDING_PROCESS,
    ONBOARDING_BEGIN,
    SEARCH_RESULTS,
    ACCOUNT_CREATION,
    EMAIL_VERIFICATION,
    AUTH_SUCCESS,
    REQUESTS,;


}